version: '3'

services:
  flask_backend:
    container_name: flask_backend
    restart: always
    build: ./flask_backend
    environment:
      - OPENAI_API_KEY
    ports:
      - "5000:5000"

  vite_medical:
    container_name: vite_medical
    restart: always
    build: ./vite_medical
    ports:
      - "3000:3000"